version: "3"
services:
  mouse_db:
    image: postgres
    restart: always
    volumes:
      - "./postgres/pg_data:/var/lib/postgresql/data/maus_volume"
    environment:
      POSTGRES_DB: maus_haus
      POSTGRES_USER: maus_der_verwalter
      POSTGRES_PASSWORD: miceRn1c3
      PGDATA: /var/lib/postgresql/data/maus_volume
    ports:
      - "5432:5432"
  graphs:
    image: "grafana/grafana:6.6.0"
    volumes:
      - "./grafana/paths_data:/var/lib/grafana"
      - "./grafana/paths_provisioning:/etc/grafana/provisioning"
      - "./grafana/paths_plugins:/var/lib/grafana/plugins"
    ports:
      - "3000:3000"
    depends_on:
      - mouse_db
  web:
    build: .
    command: ./bin/wait-for-postgres.sh
    restart: always
    volumes:
      - "./src:/var/opt/MausHaus/src"
      - "./bin:/var/opt/MausHaus/bin"
    ports:
      - "8000:8000"
    depends_on:
      - mouse_db
