{
 "title": "Bin Maintenance",
 "tags": [ "maus" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bin",
    "label": "Bin",
    "query": "SELECT description FROM maus_web_bincage ORDER BY description"
   },
   {
    "name": "rack",
    "label": "Rack",
    "query": "SELECT rack FROM maus_web_bincage ORDER BY rack"
   }
  ]
 },
 "panels": [
  {
   "title": "How long has it been since each cage was last cleaned?",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  description,\n  CURRENT_DATE - last_cleaned as \"days\"\nFROM\n  maus_web_bincage\nWHERE\n  $__timeFilter(last_cleaned)\nORDER BY description"
    }
   ]
  },
  { "title": "Where are my mice?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "repeat": "bin",
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  {
   "title": "$bin",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \n  mouse.name as \"Mouse\",\n  CURRENT_DATE - mouse.dob as \"Age\"\nFROM\n  maus_web_bincage bin, maus_web_mouse mouse\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $bin"
    }
   ]
  },
  { "title": "Where are my bins?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "$rack",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "repeat": "rack",
   "targets": [
    {
     "rawSql": "SELECT\n  description as \"Bin\",\n  elevation as \"Elevation\",\n  position as \"Position\"\nFROM\n  maus_web_bincage bin\nWHERE\n  rack = $rack\nORDER BY Elevation DESC, Position ASC"
    }
   ]
  },
  {
   "title": "$rack",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  description as \"Bin\",\n  elevation as \"Elevation\",\n  position as \"Position\"\nFROM\n  maus_web_bincage bin\nWHERE\n  rack = $rack\nORDER BY Elevation DESC, Position ASC"
    }
   ]
  },
  {
   "title": "$rack",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  description as \"Bin\",\n  elevation as \"Elevation\",\n  position as \"Position\"\nFROM\n  maus_web_bincage bin\nWHERE\n  rack = $rack\nORDER BY Elevation DESC, Position ASC"
    }
   ]
  },
  {
   "title": "$rack",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  description as \"Bin\",\n  elevation as \"Elevation\",\n  position as \"Position\"\nFROM\n  maus_web_bincage bin\nWHERE\n  rack = $rack\nORDER BY Elevation DESC, Position ASC"
    }
   ]
  }
 ]
}