{
 "title": "Breeding",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mouse",
    "label": "Mouse",
    "query": "select name from maus_web_mouse where deceased_on is NULL order by dob"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "When did each mouse hit various age milestones?",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  sub_q.days as \"time\",\n  (sub_q.days - sub_q.dob) * 86400 as \"Age in Secs\",\n  sub_q.name\nFROM (\n  SELECT \n    dob,\n    name,\n    generate_series(\n          dob, \n          CURRENT_DATE, '1 week'\n      )::date as \"days\"\n  FROM maus_web_mouse\n  WHERE\n    -- name in ($m_name)\n    deceased_on is NULL\n) sub_q\nWHERE\n  $__timeFilter(dob)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "How old is each mouse relative to the others?",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "d" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  sub_q.days as \"time\",\n  sub_q.days - sub_q.dob as \"Age in Days\",\n  sub_q.name\nFROM (\n  SELECT \n    dob,\n    name,\n    generate_series(\n          dob, \n          CURRENT_DATE, '1 week'\n      )::date as \"days\"\n  FROM maus_web_mouse\n  WHERE\n    -- name in ($m_name)\n    deceased_on is NULL\n) sub_q\nWHERE\n  $__timeFilter(dob)\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "What is the status of each mouse?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "repeat": "mouse",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  },
  {
   "title": "$mouse",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n\t  subq.age\nFROM (\n\tSELECT \n\t\tdob,\n\t\tname,\n\t\tCURRENT_DATE - dob as age\n\tFROM maus_web_mouse\n) subq\nWHERE\n\t$__timeFilter(dob)\nAND subq.name in ($mouse)"
    }
   ]
  }
 ]
}