{
 "title": "Breeding",
 "tags": [ "maus" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_breed_age", "label": "Minimum Breeding Age", "query": "56" },
   { "name": "max_breed_age", "label": "Maximum Breeding Age", "query": "240" },
   { "name": "min_rec_days", "label": "Minimum Recovery Days", "query": "56" },
   { "name": "max_rec_days", "label": "Maximum Recovery Days", "query": "77" },
   {
    "name": "fuzzybins",
    "query": "SELECT\n  bin.description\nFROM maus_web_mouse mouse, maus_web_mating mating, maus_web_bincage bin\nWHERE\n  mouse.mouse_id = mating.doe_id\nAND\n  mouse.bin_location_id = bin.bin_id\nAND\n  CURRENT_DATE - mating.delivery_date >= 10\nAND\n  CURRENT_DATE - mating.delivery_date <= 15\nORDER BY mating.number_pups_born"
   }
  ]
 },
 "panels": [
  {
   "title": "Which bins have mice ready for gender ID?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$fuzzybins",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "fuzzybins",
   "targets": [
    {
     "rawSql": "SELECT\n  bin.description as \"Location\",\n  mating.number_pups_born as \"Count\"\nFROM maus_web_mouse mouse, maus_web_mating mating, maus_web_bincage bin\nWHERE\n  mouse.mouse_id = mating.doe_id\nAND\n  mouse.bin_location_id = bin.bin_id\nAND\n  bin.description = $fuzzybins\nORDER BY 2"
    }
   ]
  },
  { "title": "Who Can I Breed?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "When will my does be ready to breed for the first time?",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  mouse.name as \"Mouse Name\",\n  CURRENT_DATE - mouse.dob as \"Age\",\n  $min_breed_age - (CURRENT_DATE - mouse.dob) as \"Days Until Ready\"\nFROM\n  maus_web_mouse mouse\nWHERE\n  NOT EXISTS (\n   SELECT\n   FROM maus_web_mating\n   WHERE mouse.mouse_id = doe_id\n  )\nAND\n  gender = 'F'\nAND\n  deceased_on is null\nORDER BY 3"
    }
   ]
  },
  {
   "title": "When will my does be ready to breed again?",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  mouse.name as \"Mouse Name\",\n  CURRENT_DATE - mouse.dob as \"Age\",\n  CURRENT_DATE - mating.delivery_date as \"Days Since Last Delivery\",\n  $min_rec_days - (CURRENT_DATE - mating.delivery_date) as \"Min Days Left of Recovery\",\n  $max_rec_days - (CURRENT_DATE - mating.delivery_date) as \"Max Days Left of Recovery\"\nFROM\n  maus_web_mouse mouse, maus_web_mating mating\nWHERE\n  mating.doe_id = mouse.mouse_id\nAND\n  gender = 'F'\nAND\n  deceased_on is null\nAND\n  CURRENT_DATE - mating.delivery_date <= $max_rec_days\nORDER BY 4"
    }
   ]
  },
  {
   "title": "Overview Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "When did each mouse hit various age milestones?",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "rawSql": "SELECT\n  sub_q.days as \"time\",\n  (sub_q.days - sub_q.dob) * 86400 as \"Age in Secs\",\n  sub_q.name\nFROM (\n  SELECT \n    dob,\n    name,\n    generate_series(\n          dob, \n          CURRENT_DATE, '1 week'\n      )::date as \"days\"\n  FROM maus_web_mouse\n  WHERE\n    -- name in ($m_name)\n    deceased_on is NULL\n) sub_q\nWHERE\n  $__timeFilter(dob)\nORDER BY 1"
      }
     ]
    },
    {
     "title": "How old is each mouse relative to the others?",
     "type": "graph",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "d" }
     ],
     "targets": [
      {
       "rawSql": "select\n\tname,\n\tdays as \"time\",\n\tdays - dob as Age\nFROM (\n\tSELECT \n\tdob,\n\tname,\n\tdeceased_on,\n\tgenerate_series(\n\t\t  dob, \n\t\t  CURRENT_DATE, '1 week'\n\t  )::date as \"days\"\n\tFROM maus_web_mouse\n) as n1\nWHERE\n  deceased_on >= days\nOR\n  deceased_on is null"
      }
     ]
    }
   ]
  },
  {
   "title": "What's the growth status of all my mice?",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Who are my newborn mice?",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  name as \"Mouse Name\",\n  CURRENT_DATE - dob as \"Age\",\n  bin.description as \"Location\"\nFROM maus_web_mouse mouse, maus_web_bincage bin\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  CURRENT_DATE - dob <= 5\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Who are my weanling mice?",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  name as \"Mouse Name\",\n  CURRENT_DATE - dob as \"Age\",\n  bin.description as \"Location\"\nFROM maus_web_mouse mouse, maus_web_bincage bin\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  CURRENT_DATE - dob >= 21\nAND\n  CURRENT_DATE - dob <= 27\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Who are my grow-out mice?",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  name as \"Mouse Name\",\n  CURRENT_DATE - dob as \"Age\",\n  bin.description as \"Location\"\nFROM maus_web_mouse mouse, maus_web_bincage bin\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  CURRENT_DATE - dob >= 28\nAND\n  CURRENT_DATE - dob <= 55\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Who are my breeder mice?",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  name as \"Mouse Name\",\n  CURRENT_DATE - dob as \"Age\",\n  bin.description as \"Location\"\nFROM maus_web_mouse mouse, maus_web_bincage bin\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  CURRENT_DATE - dob >= 56\nAND\n  CURRENT_DATE - dob <= 240\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Which does are available for mating?",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  name as \"Mouse Name\",\n  CURRENT_DATE - dob as \"Age\",\n  bin.description as \"Location\"\nFROM maus_web_mouse mouse, maus_web_bincage bin\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  CURRENT_DATE - dob >= $min_breed_age\nAND\n  CURRENT_DATE - dob <= $max_breed_age\nORDER BY 2"
    }
   ]
  },
  {
   "title": "Who are my retired mice?",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  name as \"Mouse Name\",\n  CURRENT_DATE - dob as \"Age\",\n  bin.description as \"Location\"\nFROM maus_web_mouse mouse, maus_web_bincage bin\nWHERE\n  mouse.bin_location_id = bin.bin_id\nAND\n  CURRENT_DATE - dob >= 241\nORDER BY 2"
    }
   ]
  }
 ]
}