{
 "title": "Mating",
 "tags": [ "maus" ],
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "When did each buck mate and how long until delivery?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "d", "label": "Paired to Delivery Time" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  mouse.name as \"metric\",\n  mating.cohabitation_start as \"time\",\n  mating.delivery_date - mating.cohabitation_start\nFROM maus_web_mating mating, maus_web_mouse mouse\nWHERE\n  $__timeFilter(cohabitation_start)\nAND\n  mouse.mouse_id = mating.buck_id\nAND\n  mating.successful = True\nORDER BY mating.mating_id"
    }
   ]
  },
  {
   "title": "When did each doe mate and how long until delivery?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "d", "label": "Paired to Delivery Time" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  mouse.name as \"metric\",\n  mating.cohabitation_start as \"time\",\n  mating.delivery_date - mating.cohabitation_start\nFROM maus_web_mating mating, maus_web_mouse mouse\nWHERE\n  $__timeFilter(cohabitation_start)\nAND\n  mouse.mouse_id = mating.doe_id\nAND\n  mating.successful = True\nORDER BY mating.mating_id"
    }
   ]
  },
  {
   "title": "How many offspring did each buck have per mating?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "locale", "label": "# of Offspring" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  mouse.name as \"metric\",\n  mating.delivery_date as \"time\",\n  mating.number_pups_born\nFROM maus_web_mating mating, maus_web_mouse mouse\nWHERE\n  $__timeFilter(cohabitation_start)\nAND\n  mouse.mouse_id = mating.buck_id\nAND\n  mating.successful = True\nORDER BY mating.mating_id"
    }
   ]
  },
  {
   "title": "How many offspring did each doe have per mating?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "locale", "label": "# of Offspring" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  mouse.name as \"metric\",\n  mating.delivery_date as \"time\",\n  mating.number_pups_born\nFROM maus_web_mating mating, maus_web_mouse mouse\nWHERE\n  $__timeFilter(cohabitation_start)\nAND\n  mouse.mouse_id = mating.doe_id\nAND\n  mating.successful = True\nORDER BY mating.mating_id"
    }
   ]
  },
  {
   "title": "What are the vital stats of each mating event?",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  mating.mating_id as \"ID\",\n  mouse.name as \"Father\"\nFROM maus_web_mating mating, maus_web_mouse mouse\nWHERE\n  $__timeFilter(cohabitation_start)\nAND\n  mating.buck_id = mouse.mouse_id\nAND\n  mating.successful = True\nORDER BY mating.cohabitation_start DESC"
    },
    {
     "rawSql": "SELECT\n  distinct mating.mating_id as \"ID\",\n  mouse.name as \"Mother\",\n  mating.cohabitation_start AS \"Paired\",\n  mating.delivery_date AS \"Delivered\",\n  mating.number_pups_born as \"# Offspring\",\n  mating.delivery_date - mating.cohabitation_start as \"Mating Time\"\nFROM maus_web_mating mating, maus_web_mouse mouse\nWHERE\n  $__timeFilter(cohabitation_start)\nAND\n  mating.doe_id = mouse.mouse_id\nAND\n  mating.successful = True\nORDER BY 1"
    }
   ]
  }
 ]
}